version: '3'

services:
    php:
        build: docker/php
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www/html
        depends_on:
            - database
    database:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - '${DB_PORT}:5432'